# Generated by Django 3.1.7 on 2022-02-02 00:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_modifed', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('isSubassembly', models.BooleanField()),
                ('assemblies', models.ManyToManyField(related_name='parentAssembly', to='vehicle_config.Assembly')),
            ],
            options={
                'verbose_name': 'Assembly',
                'verbose_name_plural': 'Assemblies',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_modifed', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('part_number', models.CharField(max_length=200, null=True)),
                ('parent_assembly', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle_config.assembly')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('driver_name', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('track', models.CharField(max_length=100)),
                ('ambient_temp', models.FloatField(max_length=100)),
                ('track_temp', models.FloatField(max_length=100)),
                ('date_modifed', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_modifed', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SetupParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_modifed', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('value', models.FloatField()),
                ('units', models.CharField(max_length=100, null=True)),
                ('assemblies', models.ManyToManyField(blank=True, to='vehicle_config.Assembly')),
                ('parent_setup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle_config.setup')),
                ('parts', models.ManyToManyField(blank=True, to='vehicle_config.Part')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='setup',
            name='parent_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle_config.vehicle'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='parent_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle_config.vehicle'),
        ),
    ]
