# Generated by Django 3.1.7 on 2022-02-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setup',
            old_name='event_name',
            new_name='name',
        ),
    ]
