# Generated by Django 3.1.7 on 2021-03-28 03:24

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_config', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assembly',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.DeleteModel(
            name='SetupParam',
        ),
        migrations.AddField(
            model_name='setup',
            name='car',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setup',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='setup',
            name='date_modifed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setup',
            name='setups_params',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='assemblies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='date_modifed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='setups',
            field=models.ManyToManyField(blank=True, to='vehicle_config.Setup'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.TextField(),
        ),
    ]
