# Generated by Django 3.1.7 on 2022-03-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_config', '0002_auto_20220202_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupparam',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='setupparam',
            name='units',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
