# Generated by Django 3.1.7 on 2021-03-28 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_config', '0002_auto_20210327_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setup',
            name='setups_params',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='assemblies',
        ),
    ]
