# Generated by Django 3.1.7 on 2021-03-28 04:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_config', '0004_setup_setup_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='setups_params',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='assemblies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
