# Generated by Django 3.1.7 on 2022-03-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_config', '0004_auto_20220228_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupparam',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
