# Generated by Django 3.1.7 on 2021-03-28 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_config', '0005_auto_20210327_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setup',
            name='setup_params',
        ),
    ]
