# Generated by Django 3.1.7 on 2022-03-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_config', '0005_setupparam_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setupparam',
            name='type',
        ),
        migrations.AlterField(
            model_name='setupparam',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
