# Generated by Django 3.1.7 on 2022-03-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_config', '0006_auto_20220301_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setup',
            name='ambient_temp',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='track',
        ),
        migrations.RemoveField(
            model_name='setup',
            name='track_temp',
        ),
        migrations.AddField(
            model_name='setup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
