# Generated by Django 3.1.7 on 2021-03-28 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_config', '0006_remove_setup_setup_params'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_modifed', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_modifed', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='SetupParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_modifed', models.DateTimeField(auto_now_add=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('value', models.FloatField()),
                ('assemblies', models.ManyToManyField(blank=True, to='vehicle_config.Assembly')),
                ('parts', models.ManyToManyField(blank=True, to='vehicle_config.Part')),
            ],
        ),
        migrations.AddField(
            model_name='assembly',
            name='parts',
            field=models.ManyToManyField(blank=True, to='vehicle_config.Part'),
        ),
        migrations.AddField(
            model_name='setup',
            name='setup_params',
            field=models.ManyToManyField(blank=True, to='vehicle_config.SetupParam'),
        ),
    ]
