# Generated by Django 3.1.7 on 2021-03-28 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_config', '0007_auto_20210328_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assembly',
            options={'verbose_name': 'Assembly', 'verbose_name_plural': 'Assemblies'},
        ),
    ]
