# Generated by Django 3.1.7 on 2021-06-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_config', '0008_auto_20210328_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
