# Generated by Django 3.1.7 on 2021-06-05 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_config', '0010_auto_20210604_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setup',
            name='setup_params',
        ),
    ]
