# Generated by Django 3.1.7 on 2021-06-05 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_config', '0011_remove_setup_setup_params'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setup',
            old_name='setups_params',
            new_name='setup_params',
        ),
    ]
