# Generated by Django 3.1.7 on 2021-06-28 00:54

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_config', '0013_assembly_assemblies'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='test',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[], max_length=200),
        ),
    ]
