# Generated by Django 3.1.7 on 2021-06-28 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_config', '0014_assembly_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assembly',
            name='test',
        ),
    ]
