# Generated by Django 3.1.7 on 2021-07-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_config', '0016_auto_20210707_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='name',
            field=models.CharField(default='bruh', max_length=100),
            preserve_default=False,
        ),
    ]
