# Generated by Django 3.1.7 on 2021-07-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_config', '0017_setup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
