# Generated by Django 3.1.7 on 2021-07-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_config', '0018_part_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
