# Generated by Django 3.1.7 on 2021-08-03 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_config', '0021_auto_20210803_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='parent_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle_config.vehicle'),
        ),
        migrations.AlterField(
            model_name='part',
            name='parent_assembly',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle_config.assembly'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='parent_vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle_config.vehicle'),
        ),
        migrations.AlterField(
            model_name='setupparam',
            name='parent_setup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle_config.setup'),
        ),
    ]
