# Generated by Django 3.1.7 on 2021-08-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_config', '0023_assembly_issubassembly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='assemblies',
            field=models.ManyToManyField(related_name='parentAssembly', to='vehicle_config.Assembly'),
        ),
    ]
