# Generated by Django 3.1.7 on 2021-08-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_config', '0024_auto_20210823_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='part_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
