# Generated by Django 3.1.7 on 2021-08-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_config', '0025_part_part_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='setupparam',
            name='unit_field',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
