# Generated by Django 3.1.7 on 2021-08-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_config', '0026_setupparam_unit_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setupparam',
            old_name='unit_field',
            new_name='units',
        ),
    ]
